WITH base AS(
    SELECT
        CAST(year AS INTEGER) AS year,
        COUNT(CASE WHEN vendor_name IS NOT NULL THEN 1 END) AS count_null_vendor_name,
        COUNT(CASE WHEN pickup_datetime IS NOT NULL THEN 1 END) AS count_null_pickup_datetime,
        COUNT(CASE WHEN dropoff_datetime IS NOT NULL THEN 1 END) AS count_null_dropoff_datetime,
        COUNT(CASE WHEN passenger_count IS NOT NULL THEN 1 END) AS count_null_passenger_count,
        COUNT(CASE WHEN trip_distance IS NOT NULL THEN 1 END) AS count_null_trip_distance,
        COUNT(CASE WHEN pickup_longitude IS NOT NULL THEN 1 END) AS count_null_pickup_longitude,
        COUNT(CASE WHEN pickup_latitude IS NOT NULL THEN 1 END) AS count_null_pickup_latitude,
        COUNT(CASE WHEN ratecode_id IS NOT NULL THEN 1 END) AS count_null_ratecode_id,
        COUNT(CASE WHEN store_and_forward IS NOT NULL THEN 1 END) AS count_null_store_and_forward,
        COUNT(CASE WHEN dropoff_longitude IS NOT NULL THEN 1 END) AS count_null_dropoff_longitude,
        COUNT(CASE WHEN dropoff_latitude IS NOT NULL THEN 1 END) AS count_null_dropoff_latitude,
        COUNT(CASE WHEN fare_amount IS NOT NULL THEN 1 END) AS count_null_fare_amount,
        COUNT(CASE WHEN surcharge IS NOT NULL THEN 1 END) AS count_null_surcharge,
        COUNT(CASE WHEN mta_tax IS NOT NULL THEN 1 END) AS count_null_mta_tax,
        COUNT(CASE WHEN tip_amount IS NOT NULL THEN 1 END) AS count_null_tip_amount,
        COUNT(CASE WHEN tolls_amount IS NOT NULL THEN 1 END) AS count_null_tolls_amount,
        COUNT(CASE WHEN total_amount IS NOT NULL THEN 1 END) AS count_null_total_amount,
        COUNT(CASE WHEN payment_type IS NOT NULL THEN 1 END) AS count_null_payment_type,
        COUNT(CASE WHEN pickup_location_id IS NOT NULL THEN 1 END) AS count_null_pickup_location_id,
        COUNT(CASE WHEN dropoff_location_id IS NOT NULL THEN 1 END) AS count_null_dropoff_location_id,
        COUNT(CASE WHEN store_and_fwd_flag IS NOT NULL THEN 1 END) AS count_null_store_and_fwd_flag,
        COUNT(CASE WHEN improvement_surcharge IS NOT NULL THEN 1 END) AS count_null_improvement_surcharge,
        COUNT(CASE WHEN congestion_surcharge IS NOT NULL THEN 1 END) AS count_null_congestion_surcharge,
        COUNT(CASE WHEN trip_in_seconds IS NOT NULL THEN 1 END) AS count_null_trip_in_seconds,
        COUNT(CASE WHEN extra IS NOT NULL THEN 1 END) AS count_null_extra,
        COUNT(1) AS total
    FROM "nyctlc"."yellow"
    GROUP BY year
    ORDER BY year
)
SELECT
    year,
    (count_null_vendor_name / total) AS threshold_vendor_name,
    (count_null_pickup_datetime / total) AS threshold_pickup_datetime,
    (count_null_dropoff_datetime / total) AS threshold_dropoff_datetime,
    (count_null_passenger_count / total) AS threshold_passenger_count,
    (count_null_trip_distance / total) AS threshold_trip_distance,
    (count_null_pickup_longitude / total) AS threshold_pickup_longitude,
    (count_null_pickup_latitude / total) AS threshold_pickup_latitude,
    (count_null_ratecode_id / total) AS threshold_ratecode_id,
    (count_null_store_and_forward / total) AS threshold_store_and_forward,
    (count_null_dropoff_longitude / total) AS threshold_dropoff_longitude,
    (count_null_dropoff_latitude / total) AS threshold_dropoff_latitude,
    (count_null_fare_amount / total) AS threshold_fare_amount,
    (count_null_surcharge / total) AS threshold_surcharge,
    (count_null_mta_tax / total) AS threshold_mta_tax,
    (count_null_tip_amount / total) AS threshold_tip_amount,
    (count_null_tolls_amount / total) AS threshold_tolls_amount,
    (count_null_total_amount / total) AS threshold_total_amount,
    (count_null_payment_type / total) AS threshold_payment_type,
    (count_null_pickup_location_id / total) AS threshold_pickup_location_id,
    (count_null_dropoff_location_id / total) AS threshold_dropoff_location_id,
    (count_null_store_and_fwd_flag / total) AS threshold_store_and_fwd_flag,
    (count_null_improvement_surcharge / total) AS threshold_improvement_surcharge,
    (count_null_congestion_surcharge / total) AS threshold_congestion_surcharge,
    (count_null_trip_in_seconds / total) AS threshold_trip_in_seconds,
    (count_null_extra / total) AS threshold_extra
FROM base